define_tokens! {
    // ---------------- Text Tokens ----------------
    (Text_SEMI           ,   2 , ";"                            , HirKind::Text),
    (Text_macro_rules_BANG,   3 , "macro_rules_bang"             , HirKind::Text),
    (Text_LPAREN         ,   4 , "("                            , HirKind::Text),
    (Text_RPAREN         ,   5 , ")"                            , HirKind::Text),
    (Text_LBRACK         ,   6 , "["                            , HirKind::Text),
    (Text_RBRACK         ,   7 , "]"                            , HirKind::Text),
    (Text_LBRACE         ,   8 , "{"                            , HirKind::Text),
    (Text_RBRACE         ,   9 , "}"                            , HirKind::Text),
    (Text_EQ_GT          ,  10 , "=>"                           , HirKind::Text),
    (Text_COLON          ,  11 , ":"                            , HirKind::Text),
    (Text_DOLLAR         ,  12 , "$"                            , HirKind::Text),
    (Text_PLUS           ,  14 , "+"                            , HirKind::Text),
    (Text_STAR           ,  15 , "*"                            , HirKind::Text),
    (Text_QMARK          ,  16 , "?"                            , HirKind::Text),
    (Text_block          ,  17 , "block"                        , HirKind::Text),
    (Text_expr           ,  18 , "expr"                         , HirKind::Text),
    (Text_expr_2021      ,  19 , "expr_2021"                    , HirKind::Text),
    (Text_ident          ,  20 , "ident"                        , HirKind::Text),
    (Text_item           ,  21 , "item"                         , HirKind::Text),
    (Text_lifetime       ,  22 , "lifetime"                     , HirKind::Text),
    (Text_literal        ,  23 , "literal"                      , HirKind::Text),
    (Text_meta           ,  24 , "meta"                         , HirKind::Text),
    (Text_pat            ,  25 , "pat"                          , HirKind::Text),
    (Text_pat_param      ,  26 , "pat_param"                    , HirKind::Text),
    (Text_path           ,  27 , "path"                         , HirKind::Text),
    (Text_stmt           ,  28 , "stmt"                         , HirKind::Text),
    (Text_tt             ,  29 , "tt"                           , HirKind::Text),
    (Text_ty             ,  30 , "ty"                           , HirKind::Text),
    (Text_vis            ,  31 , "vis"                          , HirKind::Text),
    (Text_u8             ,  32 , "u8"                           , HirKind::Text),
    (Text_i8             ,  33 , "i8"                           , HirKind::Text),
    (Text_u16            ,  34 , "u16"                          , HirKind::Text),
    (Text_i16            ,  35 , "i16"                          , HirKind::Text),
    (Text_u32            ,  36 , "u32"                          , HirKind::Text),
    (Text_i32            ,  37 , "i32"                          , HirKind::Text),
    (Text_u64            ,  38 , "u64"                          , HirKind::Text),
    (Text_i64            ,  39 , "i64"                          , HirKind::Text),
    (Text_u128           ,  40 , "u128"                         , HirKind::Text),
    (Text_i128           ,  41 , "i128"                         , HirKind::Text),
    (Text_isize          ,  42 , "isize"                        , HirKind::Text),
    (Text_usize          ,  43 , "usize"                        , HirKind::Text),
    (Text_f32            ,  44 , "f32"                          , HirKind::Text),
    (Text_f64            ,  45 , "f64"                          , HirKind::Text),
    (Text_bool           ,  46 , "bool"                         , HirKind::Text),
    (Text_str            ,  47 , "str"                          , HirKind::Text),
    (Text_char           ,  48 , "char"                         , HirKind::Text),
    (Text_DASH           ,  49 , "dash"                         , HirKind::Text),
    (Text_SLASH          ,  50 , "slash"                        , HirKind::Text),
    (Text_PERCENT        ,  51 , "percent"                      , HirKind::Text),
    (Text_CARET          ,  52 , "caret"                        , HirKind::Text),
    (Text_BANG           ,  53 , "bang"                         , HirKind::Text),
    (Text_AMP            ,  54 , "amp"                          , HirKind::Text),
    (Text_PIPE           ,  55 , "pipe"                         , HirKind::Text),
    (Text_AMP_AMP        ,  56 , "amp_amp"                      , HirKind::Text),
    (Text_PIPE_PIPE      ,  57 , "pipe_pipe"                    , HirKind::Text),
    (Text_LT_LT          ,  58 , "lt_lt"                        , HirKind::Text),
    (Text_GT_GT          ,  59 , "gt_gt"                        , HirKind::Text),
    (Text_PLUS_EQ        ,  60 , "plus_eq"                      , HirKind::Text),
    (Text_DASH_EQ        ,  61 , "dash_eq"                      , HirKind::Text),
    (Text_STAR_EQ        ,  62 , "star_eq"                      , HirKind::Text),
    (Text_SLASH_EQ       ,  63 , "slash_eq"                     , HirKind::Text),
    (Text_PERCENT_EQ     ,  64 , "percent_eq"                   , HirKind::Text),
    (Text_CARET_EQ       ,  65 , "caret_eq"                     , HirKind::Text),
    (Text_AMP_EQ         ,  66 , "amp_eq"                       , HirKind::Text),
    (Text_PIPE_EQ        ,  67 , "pipe_eq"                      , HirKind::Text),
    (Text_LT_LT_EQ       ,  68 , "lt_lt_eq"                     , HirKind::Text),
    (Text_GT_GT_EQ       ,  69 , "gt_gt_eq"                     , HirKind::Text),
    (Text_EQ             ,  70 , "="                            , HirKind::Text),
    (Text_EQ_EQ          ,  71 , "eq_eq"                        , HirKind::Text),
    (Text_BANG_EQ        ,  72 , "bang_eq"                      , HirKind::Text),
    (Text_GT             ,  73 , "gt"                           , HirKind::Text),
    (Text_LT             ,  74 , "lt"                           , HirKind::Text),
    (Text_GT_EQ          ,  75 , "gt_eq"                        , HirKind::Text),
    (Text_LT_EQ          ,  76 , "lt_eq"                        , HirKind::Text),
    (Text_AT             ,  77 , "at"                           , HirKind::Text),
    (Text__              ,  78 , "_"                            , HirKind::Text),
    (Text_DOT            ,  79 , "dot"                          , HirKind::Text),
    (Text_DOT_DOT        ,  80 , "dot_dot"                      , HirKind::Text),
    (Text_DOT_DOT_DOT    ,  81 , "dot_dot_dot"                  , HirKind::Text),
    (Text_DOT_DOT_EQ     ,  82 , "dot_dot_eq"                   , HirKind::Text),
    (Text_COMMA          ,  83 , ","                            , HirKind::Text),
    (Text_COLON_COLON    ,  84 , "colon_colon"                  , HirKind::Text),
    (Text_DASH_GT        ,  85 , "dash_gt"                      , HirKind::Text),
    (Text_POUND          ,  86 , "pound"                        , HirKind::Text),
    (Text_SQUOTE         ,  87 , "squote"                       , HirKind::Text),
    (Text_as             ,  88 , "as"                           , HirKind::Text),
    (Text_async          ,  89 , "async"                        , HirKind::Text),
    (Text_await          ,  90 , "await"                        , HirKind::Text),
    (Text_break          ,  91 , "break"                        , HirKind::Text),
    (Text_const          ,  92 , "const"                        , HirKind::Text),
    (Text_continue       ,  93 , "continue"                     , HirKind::Text),
    (Text_default        ,  94 , "default"                      , HirKind::Text),
    (Text_enum           ,  95 , "enum"                         , HirKind::Text),
    (Text_fn             ,  96 , "fn"                           , HirKind::Text),
    (Text_for            ,  97 , "for"                          , HirKind::Text),
    (Text_gen            ,  98 , "gen"                          , HirKind::Text),
    (Text_if             ,  99 , "if"                           , HirKind::Text),
    (Text_impl           , 100 , "impl"                         , HirKind::Text),
    (Text_let            , 101 , "let"                          , HirKind::Text),
    (Text_loop           , 102 , "loop"                         , HirKind::Text),
    (Text_match          , 103 , "match"                        , HirKind::Text),
    (Text_mod            , 104 , "mod"                          , HirKind::Text),
    (Text_pub            , 105 , "pub"                          , HirKind::Text),
    (Text_return         , 106 , "return"                       , HirKind::Text),
    (Text_static         , 107 , "static"                       , HirKind::Text),
    (Text_struct         , 108 , "struct"                       , HirKind::Text),
    (Text_trait          , 109 , "trait"                        , HirKind::Text),
    (Text_type           , 110 , "type"                         , HirKind::Text),
    (Text_union          , 111 , "union"                        , HirKind::Text),
    (Text_unsafe         , 112 , "unsafe"                       , HirKind::Text),
    (Text_use            , 113 , "use"                          , HirKind::Text),
    (Text_where          , 114 , "where"                        , HirKind::Text),
    (Text_while          , 115 , "while"                        , HirKind::Text),
    (Text_extern         , 116 , "extern"                       , HirKind::Text),
    (Text_ref            , 117 , "ref"                          , HirKind::Text),
    (Text_else           , 118 , "else"                         , HirKind::Text),
    (Text_in             , 119 , "in"                           , HirKind::Text),
    (Text_LT2            , 120 , "lt2"                          , HirKind::Text),
    (Text_dyn            , 121 , "dyn"                          , HirKind::Text),
    (Text_raw            , 123 , "raw"                          , HirKind::Text),
    (Text_yield          , 124 , "yield"                        , HirKind::Text),
    (Text_move           , 125 , "move"                         , HirKind::Text),
    (Text_try            , 126 , "try"                          , HirKind::Text),
    (Text_DQUOTE         , 129 , "dquote"                       , HirKind::Text),
    (Text_true           , 132 , "true"                         , HirKind::Text),
    (Text_false          , 133 , "false"                        , HirKind::Text),
    (Text_SLASH_SLASH    , 134 , "slash_slash"                  , HirKind::Text),
    (Text_BANG2          , 138 , "bang2"                        , HirKind::Text),
    (Text_SLASH2         , 139 , "slash2"                       , HirKind::Text),
    (Text_SLASH_STAR     , 140 , "slash_star"                   , HirKind::Text),
    (Text_STAR_SLASH     , 141 , "star_slash"                   , HirKind::Text),
    // ---------------- Node Tokens ----------------
    (identifier          ,   1 , "identifier"                   , HirKind::IdentUse),
    (aux_sym_token_repetition_pattern_token1,  13 , "aux_sym_token_repetition_pattern_token1" , HirKind::Internal),
    (mutable_specifier   , 122 , "mutable_specifier"            , HirKind::Internal),
    (integer_literal     , 127 , "integer_literal"              , HirKind::Text),
    (aux_sym_string_literal_token1, 128 , "aux_sym_string_literal_token1" , HirKind::Text),
    (char_literal        , 130 , "char_literal"                 , HirKind::Text),
    (escape_sequence     , 131 , "escape_sequence"              , HirKind::Internal),
    (aux_sym_line_comment_token1, 135 , "aux_sym_line_comment_token1"  , HirKind::Internal),
    (aux_sym_line_comment_token2, 136 , "aux_sym_line_comment_token2"  , HirKind::Internal),
    (aux_sym_line_comment_token3, 137 , "aux_sym_line_comment_token3"  , HirKind::Internal),
    (shebang             , 142 , "shebang"                      , HirKind::Internal),
    (self                , 143 , "self"                         , HirKind::Internal),
    (super               , 144 , "super"                        , HirKind::Internal),
    (crate               , 145 , "crate"                        , HirKind::Internal),
    (metavariable        , 146 , "metavariable"                 , HirKind::Internal),
    (string_content      , 147 , "string_content"               , HirKind::Internal),
    (_raw_string_literal_start, 148 , "_raw_string_literal_start"    , HirKind::Text),
    (raw_string_literal_content, 149 , "raw_string_literal_content"   , HirKind::Text),
    (_raw_string_literal_end, 150 , "_raw_string_literal_end"      , HirKind::Text),
    (float_literal       , 151 , "float_literal"                , HirKind::Text),
    (_outer_block_doc_comment_marker, 152 , "_outer_block_doc_comment_marker" , HirKind::Scope),
    (_inner_block_doc_comment_marker, 153 , "_inner_block_doc_comment_marker" , HirKind::Scope),
    (_block_comment_content, 154 , "_block_comment_content"       , HirKind::Scope),
    (_line_doc_content   , 155 , "_line_doc_content"            , HirKind::Internal),
    (_error_sentinel     , 156 , "_error_sentinel"              , HirKind::Internal),
    (source_file         , 157 , "source_file"                  , HirKind::File                 , BlockKind::Root),
    (_statement          , 158 , "_statement"                   , HirKind::Internal),
    (empty_statement     , 159 , "empty_statement"              , HirKind::Internal),
    (expression_statement, 160 , "expression_statement"         , HirKind::Internal),
    (macro_definition    , 161 , "macro_definition"             , HirKind::Internal),
    (macro_rule          , 162 , "macro_rule"                   , HirKind::Internal),
    (_token_pattern      , 163 , "_token_pattern"               , HirKind::Internal),
    (token_tree_pattern  , 164 , "token_tree_pattern"           , HirKind::Internal),
    (token_binding_pattern, 165 , "token_binding_pattern"        , HirKind::Internal),
    (token_repetition_pattern, 166 , "token_repetition_pattern"     , HirKind::Internal),
    (fragment_specifier  , 167 , "fragment_specifier"           , HirKind::Internal),
    (token_tree          , 168 , "token_tree"                   , HirKind::Internal),
    (token_repetition    , 169 , "token_repetition"             , HirKind::Internal),
    (attribute_item      , 170 , "attribute_item"               , HirKind::Internal),
    (inner_attribute_item, 171 , "inner_attribute_item"         , HirKind::Internal),
    (attribute           , 172 , "attribute"                    , HirKind::Internal),
    (mod_item            , 173 , "mod_item"                     , HirKind::Internal),
    (foreign_mod_item    , 174 , "foreign_mod_item"             , HirKind::Internal),
    (declaration_list    , 175 , "declaration_list"             , HirKind::Internal),
    (struct_item         , 176 , "struct_item"                  , HirKind::Internal),
    (union_item          , 177 , "union_item"                   , HirKind::Internal),
    (enum_item           , 178 , "enum_item"                    , HirKind::Internal),
    (enum_variant_list   , 179 , "enum_variant_list"            , HirKind::Internal),
    (enum_variant        , 180 , "enum_variant"                 , HirKind::Internal),
    (field_declaration_list, 181 , "field_declaration_list"       , HirKind::Internal),
    (field_declaration   , 182 , "field_declaration"            , HirKind::Internal),
    (ordered_field_declaration_list, 183 , "ordered_field_declaration_list" , HirKind::Internal),
    (extern_crate_declaration, 184 , "extern_crate_declaration"     , HirKind::Internal),
    (const_item          , 185 , "const_item"                   , HirKind::Internal),
    (static_item         , 186 , "static_item"                  , HirKind::Internal),
    (type_item           , 187 , "type_item"                    , HirKind::IdentUse),
    (function_item       , 188 , "function_item"                , HirKind::Scope                , BlockKind::Func),
    (function_signature_item, 189 , "function_signature_item"      , HirKind::Scope                , BlockKind::Func),
    (function_modifiers  , 190 , "function_modifiers"           , HirKind::Scope                , BlockKind::Func),
    (where_clause        , 191 , "where_clause"                 , HirKind::Internal),
    (where_predicate     , 192 , "where_predicate"              , HirKind::Internal),
    (impl_item           , 193 , "impl_item"                    , HirKind::Internal),
    (trait_item          , 194 , "trait_item"                   , HirKind::Internal),
    (associated_type     , 195 , "associated_type"              , HirKind::IdentUse),
    (trait_bounds        , 196 , "trait_bounds"                 , HirKind::Internal),
    (higher_ranked_trait_bound, 197 , "higher_ranked_trait_bound"    , HirKind::Internal),
    (removed_trait_bound , 198 , "removed_trait_bound"          , HirKind::Internal),
    (type_parameters     , 199 , "type_parameters"              , HirKind::IdentUse),
    (const_parameter     , 200 , "const_parameter"              , HirKind::Internal),
    (type_parameter      , 201 , "type_parameter"               , HirKind::IdentUse),
    (lifetime_parameter  , 202 , "lifetime_parameter"           , HirKind::Internal),
    (let_declaration     , 203 , "let_declaration"              , HirKind::Internal),
    (use_declaration     , 204 , "use_declaration"              , HirKind::Internal),
    (_use_clause         , 205 , "_use_clause"                  , HirKind::Internal),
    (scoped_use_list     , 206 , "scoped_use_list"              , HirKind::Internal),
    (use_list            , 207 , "use_list"                     , HirKind::Internal),
    (use_as_clause       , 208 , "use_as_clause"                , HirKind::Internal),
    (use_wildcard        , 209 , "use_wildcard"                 , HirKind::Internal),
    (parameters          , 210 , "parameters"                   , HirKind::Internal),
    (self_parameter      , 211 , "self_parameter"               , HirKind::Internal),
    (variadic_parameter  , 212 , "variadic_parameter"           , HirKind::Internal),
    (parameter           , 213 , "parameter"                    , HirKind::Internal),
    (extern_modifier     , 214 , "extern_modifier"              , HirKind::Internal),
    (visibility_modifier , 215 , "visibility_modifier"          , HirKind::Internal),
    (_type               , 216 , "_type"                        , HirKind::IdentUse),
    (bracketed_type      , 217 , "bracketed_type"               , HirKind::IdentUse),
    (qualified_type      , 218 , "qualified_type"               , HirKind::IdentUse),
    (lifetime            , 219 , "lifetime"                     , HirKind::Internal),
    (array_type          , 220 , "array_type"                   , HirKind::IdentUse),
    (for_lifetimes       , 221 , "for_lifetimes"                , HirKind::Internal),
    (function_type       , 222 , "function_type"                , HirKind::Scope                , BlockKind::Func),
    (tuple_type          , 223 , "tuple_type"                   , HirKind::IdentUse),
    (unit_type           , 224 , "unit_type"                    , HirKind::IdentUse),
    (generic_function    , 225 , "generic_function"             , HirKind::Scope                , BlockKind::Func),
    (generic_type        , 226 , "generic_type"                 , HirKind::IdentUse),
    (generic_type_with_turbofish, 227 , "generic_type_with_turbofish"  , HirKind::IdentUse),
    (bounded_type        , 228 , "bounded_type"                 , HirKind::IdentUse),
    (use_bounds          , 229 , "use_bounds"                   , HirKind::Internal),
    (type_arguments      , 230 , "type_arguments"               , HirKind::IdentUse),
    (type_binding        , 231 , "type_binding"                 , HirKind::IdentUse),
    (reference_type      , 232 , "reference_type"               , HirKind::IdentUse),
    (pointer_type        , 233 , "pointer_type"                 , HirKind::IdentUse),
    (never_type          , 234 , "never_type"                   , HirKind::IdentUse),
    (abstract_type       , 235 , "abstract_type"                , HirKind::IdentUse),
    (dynamic_type        , 236 , "dynamic_type"                 , HirKind::IdentUse),
    (_expression_except_range, 237 , "_expression_except_range"     , HirKind::Internal),
    (_expression         , 238 , "_expression"                  , HirKind::Internal),
    (macro_invocation    , 239 , "macro_invocation"             , HirKind::Internal),
    (delim_token_tree    , 240 , "delim_token_tree"             , HirKind::Internal),
    (_delim_tokens       , 241 , "_delim_tokens"                , HirKind::Internal),
    (_non_delim_token    , 242 , "_non_delim_token"             , HirKind::Internal),
    (scoped_identifier   , 243 , "scoped_identifier"            , HirKind::Internal),
    (scoped_type_identifier_in_expression_position, 244 , "scoped_type_identifier_in_expression_position" , HirKind::IdentUse),
    (scoped_type_identifier, 245 , "scoped_type_identifier"       , HirKind::IdentUse),
    (range_expression    , 246 , "range_expression"             , HirKind::Internal),
    (unary_expression    , 247 , "unary_expression"             , HirKind::Internal),
    (try_expression      , 248 , "try_expression"               , HirKind::Internal),
    (reference_expression, 249 , "reference_expression"         , HirKind::Internal),
    (binary_expression   , 250 , "binary_expression"            , HirKind::Internal),
    (assignment_expression, 251 , "assignment_expression"        , HirKind::Internal),
    (compound_assignment_expr, 252 , "compound_assignment_expr"     , HirKind::Internal),
    (type_cast_expression, 253 , "type_cast_expression"         , HirKind::IdentUse),
    (return_expression   , 254 , "return_expression"            , HirKind::Internal),
    (yield_expression    , 255 , "yield_expression"             , HirKind::Internal),
    (call_expression     , 256 , "call_expression"              , HirKind::Internal             , BlockKind::Call),
    (arguments           , 257 , "arguments"                    , HirKind::Internal),
    (array_expression    , 258 , "array_expression"             , HirKind::Internal),
    (parenthesized_expression, 259 , "parenthesized_expression"     , HirKind::Internal),
    (tuple_expression    , 260 , "tuple_expression"             , HirKind::Internal),
    (unit_expression     , 261 , "unit_expression"              , HirKind::Internal),
    (struct_expression   , 262 , "struct_expression"            , HirKind::Internal),
    (field_initializer_list, 263 , "field_initializer_list"       , HirKind::Internal),
    (shorthand_field_initializer, 264 , "shorthand_field_initializer"  , HirKind::Internal),
    (field_initializer   , 265 , "field_initializer"            , HirKind::Internal),
    (base_field_initializer, 266 , "base_field_initializer"       , HirKind::Internal),
    (if_expression       , 267 , "if_expression"                , HirKind::Internal),
    (let_condition       , 268 , "let_condition"                , HirKind::Internal),
    (_let_chain          , 269 , "_let_chain"                   , HirKind::Internal),
    (_condition          , 270 , "_condition"                   , HirKind::Internal),
    (else_clause         , 271 , "else_clause"                  , HirKind::Internal),
    (match_expression    , 272 , "match_expression"             , HirKind::Internal),
    (match_block         , 273 , "match_block"                  , HirKind::Scope),
    (match_arm           , 274 , "match_arm"                    , HirKind::Internal),
    (last_match_arm      , 275 , "last_match_arm"               , HirKind::Internal),
    (match_pattern       , 276 , "match_pattern"                , HirKind::Internal),
    (while_expression    , 277 , "while_expression"             , HirKind::Internal),
    (loop_expression     , 278 , "loop_expression"              , HirKind::Internal),
    (for_expression      , 279 , "for_expression"               , HirKind::Internal),
    (const_block         , 280 , "const_block"                  , HirKind::Scope),
    (closure_expression  , 281 , "closure_expression"           , HirKind::Internal),
    (closure_parameters  , 282 , "closure_parameters"           , HirKind::Internal),
    (label               , 283 , "label"                        , HirKind::Internal),
    (break_expression    , 284 , "break_expression"             , HirKind::Internal),
    (continue_expression , 285 , "continue_expression"          , HirKind::Internal),
    (index_expression    , 286 , "index_expression"             , HirKind::Internal),
    (await_expression    , 287 , "await_expression"             , HirKind::Internal),
    (field_expression    , 288 , "field_expression"             , HirKind::Internal),
    (unsafe_block        , 289 , "unsafe_block"                 , HirKind::Scope),
    (async_block         , 290 , "async_block"                  , HirKind::Scope),
    (gen_block           , 291 , "gen_block"                    , HirKind::Scope),
    (try_block           , 292 , "try_block"                    , HirKind::Scope),
    (block               , 293 , "block"                        , HirKind::Scope                , BlockKind::Scope),
    (_pattern            , 294 , "_pattern"                     , HirKind::Internal),
    (generic_pattern     , 295 , "generic_pattern"              , HirKind::Internal),
    (tuple_pattern       , 296 , "tuple_pattern"                , HirKind::Internal),
    (slice_pattern       , 297 , "slice_pattern"                , HirKind::Internal),
    (tuple_struct_pattern, 298 , "tuple_struct_pattern"         , HirKind::Internal),
    (struct_pattern      , 299 , "struct_pattern"               , HirKind::Internal),
    (field_pattern       , 300 , "field_pattern"                , HirKind::Internal),
    (remaining_field_pattern, 301 , "remaining_field_pattern"      , HirKind::Internal),
    (mut_pattern         , 302 , "mut_pattern"                  , HirKind::Internal),
    (range_pattern       , 303 , "range_pattern"                , HirKind::Internal),
    (ref_pattern         , 304 , "ref_pattern"                  , HirKind::Internal),
    (captured_pattern    , 305 , "captured_pattern"             , HirKind::Internal),
    (reference_pattern   , 306 , "reference_pattern"            , HirKind::Internal),
    (or_pattern          , 307 , "or_pattern"                   , HirKind::Internal),
    (_literal            , 308 , "_literal"                     , HirKind::Text),
    (_literal_pattern    , 309 , "_literal_pattern"             , HirKind::Text),
    (negative_literal    , 310 , "negative_literal"             , HirKind::Text),
    (string_literal      , 311 , "string_literal"               , HirKind::Text),
    (raw_string_literal  , 312 , "raw_string_literal"           , HirKind::Text),
    (boolean_literal     , 313 , "boolean_literal"              , HirKind::Text),
    (line_comment        , 314 , "line_comment"                 , HirKind::Internal),
    (_line_doc_comment_marker, 315 , "_line_doc_comment_marker"     , HirKind::Internal),
    (_inner_line_doc_comment_marker, 316 , "_inner_line_doc_comment_marker" , HirKind::Internal),
    (_outer_line_doc_comment_marker, 317 , "_outer_line_doc_comment_marker" , HirKind::Internal),
    (block_comment       , 318 , "block_comment"                , HirKind::Scope),
    (_block_doc_comment_marker, 319 , "_block_doc_comment_marker"    , HirKind::Scope),
    (aux_sym_source_file_repeat1, 320 , "aux_sym_source_file_repeat1"  , HirKind::Internal),
    (aux_sym_macro_definition_repeat1, 321 , "aux_sym_macro_definition_repeat1" , HirKind::Internal),
    (aux_sym_token_tree_pattern_repeat1, 322 , "aux_sym_token_tree_pattern_repeat1" , HirKind::Internal),
    (aux_sym_token_tree_repeat1, 323 , "aux_sym_token_tree_repeat1"   , HirKind::Internal),
    (aux_sym__non_special_token_repeat1, 324 , "aux_sym__non_special_token_repeat1" , HirKind::Internal),
    (aux_sym_declaration_list_repeat1, 325 , "aux_sym_declaration_list_repeat1" , HirKind::Internal),
    (aux_sym_enum_variant_list_repeat1, 326 , "aux_sym_enum_variant_list_repeat1" , HirKind::Internal),
    (aux_sym_enum_variant_list_repeat2, 327 , "aux_sym_enum_variant_list_repeat2" , HirKind::Internal),
    (aux_sym_field_declaration_list_repeat1, 328 , "aux_sym_field_declaration_list_repeat1" , HirKind::Internal),
    (aux_sym_ordered_field_declaration_list_repeat1, 329 , "aux_sym_ordered_field_declaration_list_repeat1" , HirKind::Internal),
    (aux_sym_function_modifiers_repeat1, 330 , "aux_sym_function_modifiers_repeat1" , HirKind::Scope                , BlockKind::Func),
    (aux_sym_where_clause_repeat1, 331 , "aux_sym_where_clause_repeat1" , HirKind::Internal),
    (aux_sym_trait_bounds_repeat1, 332 , "aux_sym_trait_bounds_repeat1" , HirKind::Internal),
    (aux_sym_type_parameters_repeat1, 333 , "aux_sym_type_parameters_repeat1" , HirKind::IdentUse),
    (aux_sym_use_list_repeat1, 334 , "aux_sym_use_list_repeat1"     , HirKind::Internal),
    (aux_sym_parameters_repeat1, 335 , "aux_sym_parameters_repeat1"   , HirKind::Internal),
    (aux_sym_for_lifetimes_repeat1, 336 , "aux_sym_for_lifetimes_repeat1" , HirKind::Internal),
    (aux_sym_tuple_type_repeat1, 337 , "aux_sym_tuple_type_repeat1"   , HirKind::IdentUse),
    (aux_sym_use_bounds_repeat1, 338 , "aux_sym_use_bounds_repeat1"   , HirKind::Internal),
    (aux_sym_type_arguments_repeat1, 339 , "aux_sym_type_arguments_repeat1" , HirKind::IdentUse),
    (aux_sym_delim_token_tree_repeat1, 340 , "aux_sym_delim_token_tree_repeat1" , HirKind::Internal),
    (aux_sym_arguments_repeat1, 341 , "aux_sym_arguments_repeat1"    , HirKind::Internal),
    (aux_sym_tuple_expression_repeat1, 342 , "aux_sym_tuple_expression_repeat1" , HirKind::Internal),
    (aux_sym_field_initializer_list_repeat1, 343 , "aux_sym_field_initializer_list_repeat1" , HirKind::Internal),
    (aux_sym_match_block_repeat1, 344 , "aux_sym_match_block_repeat1"  , HirKind::Scope),
    (aux_sym_match_arm_repeat1, 345 , "aux_sym_match_arm_repeat1"    , HirKind::Internal),
    (aux_sym_closure_parameters_repeat1, 346 , "aux_sym_closure_parameters_repeat1" , HirKind::Internal),
    (aux_sym_tuple_pattern_repeat1, 347 , "aux_sym_tuple_pattern_repeat1" , HirKind::Internal),
    (aux_sym_slice_pattern_repeat1, 348 , "aux_sym_slice_pattern_repeat1" , HirKind::Internal),
    (aux_sym_struct_pattern_repeat1, 349 , "aux_sym_struct_pattern_repeat1" , HirKind::Internal),
    (aux_sym_string_literal_repeat1, 350 , "aux_sym_string_literal_repeat1" , HirKind::Text),
    (alias_sym_field_identifier, 351 , "alias_sym_field_identifier"   , HirKind::Internal),
    (alias_sym_let_chain , 352 , "alias_sym_let_chain"          , HirKind::Internal),
    (alias_sym_shorthand_field_identifier, 353 , "alias_sym_shorthand_field_identifier" , HirKind::Internal),
    (alias_sym_type_identifier, 354 , "alias_sym_type_identifier"    , HirKind::IdentUse),
    // ---------------- Field IDs ----------------
    (field_alias         ,   1 , "alias"                        , HirKind::Internal),
    (field_alternative   ,   2 , "alternative"                  , HirKind::Internal),
    (field_argument      ,   3 , "argument"                     , HirKind::Internal),
    (field_arguments     ,   4 , "arguments"                    , HirKind::Internal),
    (field_body          ,   5 , "body"                         , HirKind::Internal),
    (field_bounds        ,   6 , "bounds"                       , HirKind::Internal),
    (field_condition     ,   7 , "condition"                    , HirKind::Internal),
    (field_consequence   ,   8 , "consequence"                  , HirKind::Internal),
    (field_default_type  ,   9 , "default_type"                 , HirKind::Internal),
    (field_doc           ,  10 , "doc"                          , HirKind::Internal),
    (field_element       ,  11 , "element"                      , HirKind::Internal),
    (field_field         ,  12 , "field"                        , HirKind::Internal),
    (field_function      ,  13 , "function"                     , HirKind::Internal),
    (field_inner         ,  14 , "inner"                        , HirKind::Internal),
    (field_left          ,  15 , "left"                         , HirKind::Internal),
    (field_length        ,  16 , "length"                       , HirKind::Internal),
    (field_list          ,  17 , "list"                         , HirKind::Internal),
    (field_macro         ,  18 , "macro"                        , HirKind::Internal),
    (field_name          ,  19 , "name"                         , HirKind::Internal),
    (field_operator      ,  20 , "operator"                     , HirKind::Internal),
    (field_outer         ,  21 , "outer"                        , HirKind::Internal),
    (field_parameters    ,  22 , "parameters"                   , HirKind::Internal),
    (field_path          ,  23 , "path"                         , HirKind::Internal),
    (field_pattern       ,  24 , "pattern"                      , HirKind::Internal),
    (field_return_type   ,  25 , "return_type"                  , HirKind::Internal),
    (field_right         ,  26 , "right"                        , HirKind::Internal),
    (field_trait         ,  27 , "trait"                        , HirKind::Internal),
    (field_type          ,  28 , "type"                         , HirKind::Internal),
    (field_type_arguments,  29 , "type_arguments"               , HirKind::Internal),
    (field_type_parameters,  30 , "type_parameters"              , HirKind::Internal),
    (field_value         ,  31 , "value"                        , HirKind::Internal),
}
