[package]
name = "llmcc-python"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
llmcc-core.workspace = true
tree-sitter-python.workspace = true
tree-sitter.workspace = true
