[package]
name = "debug-python-ast"
version = "0.1.0"
edition = "2021"

[dependencies]
llmcc-core = { path = "../llmcc-core" }
llmcc-python = { path = "../llmcc-python" }
tree-sitter = "0.25"
tree-sitter-python = "0.25"
