[package]
name = "llmcc"
version = "0.1.0"
edition = "2024"

[build-dependencies]
cc = "*"


[dependencies]
typed-arena = "2.0.2"
tree-sitter = "0.25"
tree-sitter-rust = "0.23"
strum = "0.27"
strum_macros = "0.27"
paste = "1.0.15"
regex = "1.11"
