[package]
name = "llmcc-macro"
version = "0.1.0"
edition.workspace = true
publish.workspace = true


[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
regex.workspace = true
once_cell.workspace = true

[lib]
proc-macro = true